#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  create_session.sh <topic>

Example:
  create_session.sh board_first_deploy

Environment:
  SESSION_TIMESTAMP   Override timestamp prefix, e.g. 20260316_2100
EOF
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/../.." && pwd)
sessions_dir="$repo_root/logs/sessions"

topic_raw="$1"
timestamp="${SESSION_TIMESTAMP:-$(date +%Y%m%d_%H%M)}"
topic_slug=$(printf '%s' "$topic_raw" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '_')
session_id="${timestamp}_${topic_slug}"
session_dir="$sessions_dir/$session_id"
commit_id=$(git -C "$repo_root" rev-parse --short HEAD 2>/dev/null || printf 'unknown')

mkdir -p "$session_dir/artifacts/iter_01"
printf 'waiting_windows\n' > "$session_dir/status.txt"

cat > "$session_dir/server_to_windows.md" <<EOF
# Session Task Sheet

## Meta
- session_id: \`$session_id\`
- owner: \`Server Codex\`
- status: \`waiting_windows\`
- iteration: \`1\`
- commit: \`$commit_id\`

## Goal
- Fill in the concrete board-side goal for this session.

## Minimum Windows Loop
Only do these three things in this iteration:

1. Upload the required package or files to the board.
2. Run the exact commands requested for this iteration.
3. Put logs into \`artifacts/iter_01/\` and fill \`windows_to_server.md\`.

## Ready Artifacts
- Fill in artifact paths from the server.

## Commands To Run On Windows Side
- Fill in exact commands to run.

## Expected Result
- Fill in expected startup logs or checkpoints.

## Return With
- \`cmd.txt\`
- \`stdout.txt\` or \`serial.log\`
- One short summary in \`windows_to_server.md\`

## Artifact Upload Path
- $session_dir/artifacts/iter_01/
EOF

cat > "$session_dir/windows_to_server.md" <<EOF
# Session Return Sheet

## Meta
- session_id: \`$session_id\`
- owner: \`Windows Codex\`
- status:
- iteration: \`1\`

## Result Summary
- SSH reachable:
- Package uploaded:
- Binary starts:
- Key blocker:

## Actual Command Notes
- 

## Key Findings
- 

## Uploaded Artifacts
- \`artifacts/iter_01/cmd.txt\`
- \`artifacts/iter_01/stdout.txt\`
- \`artifacts/iter_01/stderr.txt\`
- \`artifacts/iter_01/dmesg.txt\`
- \`artifacts/iter_01/serial.log\`

## Next Suggestion
- continue / blocked / done
EOF

cat > "$session_dir/notes.md" <<EOF
# Session Notes

This session was generated by \`tools/server/create_session.sh\`.

Minimal loop:

1. Server Codex writes the task sheet.
2. Windows Codex syncs this session locally and executes the board-side work.
3. Windows Codex uploads evidence back to the server session directory.
4. Server Codex reads the evidence and decides the next step.
EOF

printf '%s\n' "$session_id"
printf '%s\n' "$session_dir"
